[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",  
]

# Solidity compiler settings
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "paris"

# Test settings
verbosity = 2

# Gas reporting
gas_reports = ["*"]

# Formatter settings
line_length = 120
tab_width = 4
bracket_spacing = true

# Documentation
auto_detect_solc = false 